// FIX: Removed invalid file markers that were causing parsing errors.
import type { NutrientProfile, Plan, StageClass, Language, Cultivar, Substrate, Phase, ManagedPlan } from './types';

export const CULTIVARS: Cultivar[] = ['wedding_cake', 'blue_dream', 'amnesia_haze'];
export const SUBSTRATES: Substrate[] = ['coco', 'soil', 'rockwool'];

// ===== Chemistry & recipes from doser.html =====
const TARGET_MIX_TOTAL = 1000;
const P_from_P2O5 = 0.4365, K_from_K2O = 0.8301, S_from_SO3 = 0.4;
const MKP_P2O5 = 0.52, MKP_K2O = 0.34, MAP_N = 0.12, MAP_P2O5 = 0.61, KNO3_N = 0.13, KNO3_K2O = 0.46, SOP_K2O = 0.50, SOP_SO3 = 0.45, EPSOM_Mg = 0.0981, EPSOM_S = 0.1222;
const MMX = {Fe:0.078,Mn:0.026,Zn:0.013,Cu:0.005,B:0.007,Mo:0.0032}, FeEDTA_Fe=0.13, H3BO3_B=0.1749, Na2MoO4_Mo=0.396;
const MGNITRATE_N=0.11, MGNITRATE_Mg=0.096, CACALGG_N=0.155, CACALGG_Ca=0.19;

const VECTOR_RECIPE_RAW: Record<string, number> = {
  MgSO4: 240.8,
  K2SO4: 232.4,
  KNO3: 4.8,
  MKP: 126.8,
  MAP: 342.2,
  MMX: 40.1,
  FeEDTA: 8.0,
  H3BO3: 4.6,
  Na2MoO4: 0.2,
};

const PULSE_RECIPE_RAW: Record<string, number> = {
  MgSO4: 89.980965565,
  K2SO4: 273.807463806,
  KNO3: 0.0,
  MKP: 180.019611236,
  MMX: 24.9754859549,
  FeEDTA: 5.01816923343,
  H3BO3: 2.88400530657,
  Na2MoO4: 0.115360212263,
};

const VECTOR_NORMALIZATION = 1.0563;
const PULSE_NORMALIZATION = 1.7337;

function normalizeRecipe(
  raw: Record<string, number>,
  scale: number,
  target: number = TARGET_MIX_TOTAL,
): Record<string, number> {
  const normalized: Record<string, number> = {};
  let total = 0;
  for (const salt of Object.keys(raw)) {
    const grams = (raw[salt] || 0) * scale;
    if (Number.isFinite(grams) && grams > 0) {
      normalized[salt] = grams;
      total += grams;
    } else {
      normalized[salt] = 0;
    }
  }
  if (!total) {
    for (const salt of Object.keys(raw)) normalized[salt] = 0;
    return normalized;
  }
  const adjust = target / total;
  for (const salt of Object.keys(normalized)) {
    normalized[salt] = normalized[salt] * adjust;
  }
  return normalized;
}

function sharesFromNormalized(
  normalized: Record<string, number>,
  target: number = TARGET_MIX_TOTAL,
): Record<string, number> {
  const shares: Record<string, number> = {};
  const divisor = target || 1;
  for (const salt of Object.keys(normalized)) {
    shares[salt] = (normalized[salt] || 0) / divisor;
  }
  return shares;
}

const B_REC = normalizeRecipe(VECTOR_RECIPE_RAW, VECTOR_NORMALIZATION);
const C_REC = normalizeRecipe(PULSE_RECIPE_RAW, PULSE_NORMALIZATION);
const BURST: Record<string, number> = {MKP:0.60,SOP:0.39,EPSOM:0.025};


function profileFromRecipe(rec: Record<string, number>): NutrientProfile {
  const o: Required<NutrientProfile> = {N:0,P:0,K:0,Ca:0,Mg:0,S:0,Na:0,Fe:0,B:0,Mo:0,Mn:0,Zn:0,Cu:0,Cl:0};
  const g = sharesFromNormalized(rec);

  if(g.MgSO4){ o.Mg+=g.MgSO4*EPSOM_Mg*1000; o.S+=g.MgSO4*EPSOM_S*1000; }
  if(g.K2SO4){ o.K +=g.K2SO4*SOP_K2O*K_from_K2O*1000; o.S+=g.K2SO4*SOP_SO3*S_from_SO3*1000; }
  if(g.KNO3){ o.N +=g.KNO3*KNO3_N*1000; o.K+=g.KNO3*KNO3_K2O*K_from_K2O*1000; }
  if(g.MKP){  o.P +=g.MKP*MKP_P2O5*P_from_P2O5*1000; o.K+=g.MKP*MKP_K2O*K_from_K2O*1000; }
  if(g.MAP){  o.N +=g.MAP*MAP_N*1000; o.P+=g.MAP*MAP_P2O5*P_from_P2O5*1000; }
  if(g.MMX){  o.Fe+=g.MMX*MMX.Fe*1000; o.Mn+=g.MMX*MMX.Mn*1000; o.Zn+=g.MMX*MMX.Zn*1000; o.Cu+=g.MMX*MMX.Cu*1000; o.B+=g.MMX*MMX.B*1000; o.Mo+=g.MMX*MMX.Mo*1000; }
  if(g.FeEDTA){ o.Fe+=g.FeEDTA*FeEDTA_Fe*1000; }
  if(g.H3BO3){  o.B +=g.H3BO3*H3BO3_B*1000; }
  if(g.Na2MoO4){o.Mo+=g.Na2MoO4*Na2MoO4_Mo*1000; }
  return o;
}

export const PROF_A: NutrientProfile = {
    N: (0.600 * CACALGG_N + 0.400 * MGNITRATE_N) * 1000,
    Ca: (0.600 * CACALGG_Ca) * 1000,
    Mg: (0.400 * MGNITRATE_Mg) * 1000,
};

export const PROF_B: NutrientProfile = profileFromRecipe(B_REC);
export const PROF_C: NutrientProfile = profileFromRecipe(C_REC);

export const PROF_BURST: NutrientProfile = (()=>{
    const o: Required<NutrientProfile> = {N:0,P:0,K:0,Ca:0,Mg:0,S:0,Na:0,Fe:0,B:0,Mo:0,Mn:0,Zn:0,Cu:0,Cl:0};
    o.P += BURST.MKP*MKP_P2O5*P_from_P2O5*1000; o.K += BURST.MKP*MKP_K2O*K_from_K2O*1000;
    o.K += BURST.SOP*SOP_K2O*K_from_K2O*1000; o.S += BURST.SOP*SOP_SO3*S_from_SO3*1000;
    o.Mg += BURST.EPSOM*EPSOM_Mg*1000; o.S += BURST.EPSOM*EPSOM_S*1000;
    return o;
})();

const AMMONIUM_DETECTION_LIMIT = 0.05; // mg/L NH4+, reported as "< 0,05"
const NH4_TO_ELEMENTAL_N = 14.0067 / 18.038; // conversion factor NH4+ -> elemental N

export const DEFAULT_WATER_PROFILE: NutrientProfile = {
    N: AMMONIUM_DETECTION_LIMIT * NH4_TO_ELEMENTAL_N,
    Ca: 65.8,
    Mg: 31.8,
    K: 1.8,
    Na: 7.8,
    Cl: 18,
    S: 70.43, // 211 mg/L SO4 converted to elemental S
    Fe: 0.01,
    Mn: 0.01,
};

export const DEFAULT_OSMOSIS_SHARES: Record<Substrate, number> = {
    rockwool: 0.30,
    coco: 0.40,
    soil: 0.20,
};

/* Additives (ppm je g oder ml pro L) */
export const PROF_TIDE: NutrientProfile = { N: 0.01 * 1000, K: (0.17 * 0.8301) * 1000, S: 0.01 * 1000, Na: 0.025 * 1000 };
export const PROF_HELIX: NutrientProfile = { N: 0.10 * 1000 };
export const PROF_LIGAND: NutrientProfile = { N: 0.10 * 1000 };

export const QUENCH_DOSE_G_L = 0.30;
export const PROF_QUENCH: NutrientProfile = { Ca:0.2725*1000, Cl:0.4827*1000 };

export const I18N: Record<Language, any> = {
    de: {
        lang: "Sprache",
        title: "PhotonFlux Nährstoffrechner",
        cultivar: "Sorte",
        cultivar_names: {
            wedding_cake: "Wedding Cake",
            blue_dream: "Blue Dream",
            amnesia_haze: "Amnesia Haze",
        },
        substrate_names: {
            coco: "Coco",
            soil: "Erde",
            rockwool: "Steinwolle",
        },
        phases: {
            "Early Veg": "Frühe Veg", "Mid Veg": "Mitte Veg", "Late Veg": "Späte Veg",
            "W1": "W1", "W2": "W2", "W3": "W3", "W4": "W4", "W5": "W5", "W6": "W6", "W7": "W7", "W8": "W8", "W9": "W9", "W10": "W10", "Harvest": "Ernte"
        },
        tags: {
            "Early Veg": "Sämling", "Mid Veg": "Wachstum", "Late Veg": "Wachstum",
            "W1": "Transformation", "W2": "Early Flower", "W3": "Early Flower", "W4": "Bulking", "W5": "Bulking", "W6": "Bulking", "W7": "Bulking", "W8": "Bulking", "W9": "Ripen", "W10": "Ripen"
        },
        days_of_week: {
            "0": "Sonntag", "1": "Montag", "2": "Dienstag", "3": "Mittwoch", "4": "Donnerstag", "5": "Freitag", "6": "Samstag"
        },
        phase_week: "Phase/Woche",
        settings: "Einstellungen",
        reservoir: "Reservoir (L)",
        substrate: "Substrat",
        trend: "EC-Trend",
        neutral: "Neutral",
        higher: "Höher",
        lower: "Niedriger",
        tipburn: "Spitzenbrand",
        very_pale: "Stark aufgehellt",
        camg_need: "Ca/Mg-Mangel",
        claw: "Adlerkralle",
        ph_drift: "pH-Drift",
        normal: "Normal",
        too_high: "Zu hoch",
        too_low: "Zu niedrig",
        start_date: "Startdatum",
        auto_phase_switch: "Auto-Phasenwechsel",
        week_starts_on: "Woche startet am",
        calculate: "Berechnen",
        calculating: "Berechne",
        reset: "Reset",
        export: "Export",
        import: "Import",
        config: "Pläne",
        print: "Drucken",
        component: "Komponente",
        per_l: "pro L",
        total: "Gesamt",
        note: "Notiz",
        silicate_name: "Silicate / Hypo",
        per_plant_short: "Pfl.",
        apply_per_plant: "Pro Pflanze anwenden",
        plan_print_title: "Druckansicht Düngeplan",
        plan_print_description: "Gesamter Plan pro Liter mit allen Komponenten und Notizen.",
        plan_print_duration: "Dauer (Tage)",
        plan_print_notes: "Notizen",
        silicate_mid_veg_note: "Silicate-Topdress: 4 g pro Pflanze um die Pflanze verteilen.",
        target_ec: "Ziel-EC:",
        npk_ratio_title: "NPK-Verhältnis",
        edit_plan: "Düngeplan bearbeiten",
        close: "Schließen",
        save: "Speichern",
        A_name: "A (Calciumnitrat)", B_name: "B (N-P-K-Mg Salze)", C_name: "C (P-K-S-Mg Salze)", BURST_name: "BURST (PK-Booster)",
        analyzer_button: "Pflanzen-Analysator",
        analyzer_button_desc: "KI-gestützte Problemerkennung",
        journal_button: "Anbau-Tagebuch",
        journal_button_desc: "Fortschritt und Notizen festhalten",
        weekly_plan_title: "Wochenplan",
        weekly_plan_prompt: "Startdatum für den Wochenplan festlegen.",
        current_week: "Aktuell",
        // Tooltips
        tooltip_config: "Benutzerdefinierte Düngepläne für die aktuelle Sorte und das Substrat verwalten.",
        tooltip_print: "Eine druckfreundliche Version der aktuellen Ergebnisse und des Wiegeplans erstellen.",
        tooltip_trend: "Wie hat sich der EC-Wert in den letzten 24h verändert? Passen Sie die Düngung entsprechend an.",
        tooltip_phDrift: "Wie verhält sich der pH-Wert in der Nährlösung? Ein Drift nach oben oder unten kann auf Probleme hinweisen.",
        tooltip_start_date: "Das Datum, an dem die Pflanze in die erste Phase (Sämling/Steckling) eingetreten ist. Dies aktiviert den Wochenplan.",
        tooltip_auto_phase_switch: "Wenn aktiviert, wechselt die App automatisch die Phase basierend auf dem Startdatum.",
        tooltip_week_starts_on: "Legen Sie den Wochentag fest, an dem jede neue Grow-Woche für die automatische Phasen-Umschaltung beginnen soll.",
        tooltip_tipburn: "Zeigen die Blattspitzen Anzeichen von Verbrennungen? Dies deutet oft auf einen leichten Nährstoffüberschuss hin.",
        tooltip_claw: "Krallen sich die Blätter nach unten (Adlerkralle)? Ein klassisches Zeichen für Stickstoff-Überschuss.",
        tooltip_pale: "Sind die Blätter, insbesondere die älteren, stark aufgehellt oder gelblich? Dies deutet auf einen Stickstoffmangel hin.",
        tooltip_caMgDeficiency: "Zeigen sich rostige Flecken oder helle Verfärbungen zwischen den Blattadern? Dies kann auf einen Cal-Mag-Mangel hindeuten.",
        tooltip_calculate: "Berechnet die endgültige Nährstoffdosierung basierend auf allen Eingaben und Anpassungen.",
        tooltip_reset: "Setzt alle Eingaben und Pläne auf die Standardwerte zurück.",
        tooltip_export: "Speichert den ausgewählten Düngeplan als JSON-Datei.",
        tooltip_import: "Lädt einen Düngeplan aus einer JSON-Datei als neuen benutzerdefinierten Plan.",
        tooltip_A: "Kernkomponente: Liefert hauptsächlich Kalzium und Spurenelemente.",
        tooltip_B: "Veg-Komponente: Liefert Stickstoff und Magnesium für die Wachstumsphase.",
        tooltip_C: "Blüte-Komponente: Liefert Schwefel und Magnesium für die Blütephase.",
        tooltip_burst: "Blüte-Booster: Liefert Phosphor und Kalium zur Steigerung der Blütenproduktion.",
        tooltip_npk_ratio: "Das Verhältnis von Stickstoff (N), Phosphor (P) und Kalium (K) in der endgültigen Nährlösung.",
        tooltip_analyzer: "Laden Sie Fotos Ihrer Pflanze hoch, um eine KI-gestützte Diagnose potenzieller Probleme wie Nährstoffmängel oder Schädlinge zu erhalten.",
        tooltip_journal: "Führen Sie ein detailliertes Protokoll über jede Düngung, Beobachtung und Ernte, um den Fortschritt Ihres Anbaus zu dokumentieren.",
        // Mixing Instructions (Restored from doser.html)
        mixing_title: "Anleitung für die Mischreihenfolge",
        mixing_prep_title: "Vorbereitung",
        mixing_prep_text1: "Tank 70–80 % mit Wasser (18–22 °C) füllen, kräftige Umwälzung an.",
        mixing_ph_title: "pH-Anpassen",
        mixing_ph_text1: "Nie Pulver direkt in den Ansaugwirbel streuen. Erst 1–2 L Becher mit Tankwasser füllen, Schlämme anrühren, dann am Gegenstrom einlaufen lassen.",
        mixing_veg_title: "Reihenfolge – Veg (A + B)",
        mixing_veg_step1: "B (VECTOR) in 3 Portionen: einrühren, 60–90 s klären lassen.",
        mixing_veg_step2: "Helix, Ligand, Tide zugeben.",
        mixing_veg_step3: "A (CORE) in 2 Portionen, langsam. 2 min mischen, klären lassen.",
        mixing_veg_step4: "Auf Endvolumen. EC & pH prüfen (Coco/RW: 5.8–6.0; Erde: 6.2–6.5).",
        mixing_bloom_title: "Reihenfolge – Blüte (A + C + BURST)",
        mixing_bloom_step1: "C (PULSE) in 3 Portionen vollständig lösen.",
        mixing_bloom_step2: "BURST (PK) in 2 Portionen lösen.",
        mixing_bloom_step3: "Helix, Ligand, Tide zugeben.",
        mixing_bloom_step4: "A (CORE) zuletzt, langsam in 2 Portionen.",
        mixing_bloom_step5: "Auf Endvolumen. EC & pH prüfen.",
        mixing_checks_title: "Wartezeiten & Checks",
        mixing_checks_step1: "Zwischen Komponenten je 60–120 s warten, bis klar.",
        mixing_checks_step2: "Nach A: 2–3 min laufen lassen, dann EC stabil ablesen.",
        // Plant Analyzer & Cropper
        analyzer_loading_step1: "Lade neuronales Netz...",
        analyzer_loading_step2: "Analysiere Blattmorphologie...",
        analyzer_loading_step3: "Prüfe auf Nährstoffanomalien...",
        analyzer_loading_step4: "Stelle Diagnose zusammen...",
        analyzer_loading_wait: "Bitte warten, dies kann einen Moment dauern.",
        analyzer_fail_title: "Analyse fehlgeschlagen",
        analyzer_fail_try_again: "Erneut versuchen",
        analyzer_actions_title: "Empfohlene Aktionen",
        analyzer_another_photo: "Weitere Analyse durchführen",
        analyzer_drop_zone: "Bilder hierher ziehen oder",
        browse_files: "Dateien durchsuchen",
        analyzer_photos_added: "{0} / {1} Fotos hinzugefügt",
        analyzer_max_photos_remove: "Maximal. Entfernen Sie eines, um ein neues hinzuzufügen.",
        analyzer_crop_photo: "Foto {0} zuschneiden",
        analyzer_remove_photo: "Foto {0} entfernen",
        analyzer_context_title: "Analyse-Kontext",
        analyzer_phase: "Phase:",
        analyzer_substrate: "Substrat:",
        analyzer_notes_label: "Zusätzliche Notizen",
        analyzer_notes_placeholder: "Beschreiben Sie das Problem: Wo ist es zuerst aufgetreten? Wie hat es sich entwickelt? Z.B. 'Gelbe Flecken auf älteren Blättern, breitet sich nach oben aus'.",
        analyzer_button_cta: "Jetzt analysieren",
        analyzer_disclaimer: "KI-Analyse ist experimentell und sollte als Hilfestellung, nicht als endgültige Diagnose betrachtet werden.",
        analyzer_title: "Pflanzen-Analysator",
        ai_analysis_title: "KI-Analyse",
        analyzer_invalid_file_alert: "Ungültiger Dateityp für: {0}. Bitte nur Bilder hochladen.",
        analyzer_upload_limit_alert: "Upload-Limit von {0} Fotos erreicht. {1} Datei(en) wurden ignoriert.",
        analyzer_observed_symptoms_title: "Beobachtete Symptome",
        cropper_title: "Bild zuschneiden",
        cropper_cancel: "Abbrechen",
        cropper_save: "Zuschnitt speichern",
        loading: "Laden...",
        cancel: "Abbrechen",
        date: "Datum",
        phase: "Phase",
        // New Stage Analysis
        ai_stage_analysis_title: "KI-Stadienanalyse",
        ai_stage_label: "Stadium",
        ai_confidence_label: "Konfidenz",
        ai_reasoning_label: "Begründung",
        ai_stage_loading: "Analysiere Stadium...",
        stage_vegetative: "Wachstum",
        stage_flowering: "Blüte",
        stage_ripening: "Reife",
        confidence_High: "Hoch",
        confidence_Medium: "Mittel",
        confidence_Low: "Niedrig",
        // New Summary
        analyzer_summary_title: "Zusammenfassung",
        analyzer_summary_finding: "Wichtigster Befund",
        analyzer_summary_action: "Top-Empfehlung",
        // Journal specific
        journal_title: "Grow-Tagebuch",
        journal_set_start_date_prompt: "Bitte legen Sie im Hauptfenster ein Startdatum fest, um ein Anbau-Tagebuch zu erstellen oder anzuzeigen.",
        journal_empty_state: "Noch keine Einträge vorhanden. Fügen Sie Ihren ersten hinzu!",
        journal_add_entry: "Neuer Eintrag",
        journal_edit_entry: "Eintrag bearbeiten",
        journal_entry_type: "Art des Eintrags",
        journal_type_Observation: "Beobachtung",
        journal_type_Feeding: "Düngung",
        journal_type_Pest: "Schädlingsbekämpfung",
        journal_type_Training: "Training",
        journal_type_Harvest: "Ernte",
        journal_priority: "Prioritaet",
        journal_priority_Critical: "Kritisch",
        journal_priority_High: "Hoch",
        journal_priority_Medium: "Mittel",
        journal_priority_Low: "Niedrig",
        journal_notes_placeholder: "Was ist heute passiert? Notieren Sie Ihre Beobachtungen...",
        journal_add_photos: "Fotos hinzufügen",
        journal_photos_added: "Fotos hinzugefügt",
        journal_save_entry: "Eintrag speichern",
        journal_delete_entry: "Eintrag löschen",
        journal_confirm_delete: "Möchten Sie diesen Eintrag wirklich löschen?",
        journal_feeding_details: "Düngungsdetails",
        journal_feeding_prefilled: "Werte basierend auf dem aktuellen Plan vorausgefüllt.",
        journal_analyze_with_ai: "Mit KI analysieren",
        journal_ai_analysis_complete: "KI-Analyse abgeschlossen",
        journal_ai_result: "KI-Ergebnis",
        journal_filter_priority: "Nach Priorität filtern",
        journal_all_priorities: "Alle",
        journal_week: "Woche",
        journal_adjustments_title: "Anpassungen",
        journal_save_analysis: "Analyse im Tagebuch speichern",
        journal_analysis_saved: "Analyse gespeichert",
        journal_export: "Tagebuch exportieren",
        journal_ai_filter_label: "Nur KI-Analysen",
        journal_harvest_details: "Erntedetails",
        journal_wet_weight: "Nassgewicht (g)",
        journal_dry_weight: "Trockengewicht (g)",
        journal_trim_weight: "Schnittreste (g)",
        journal_quality_rating: "Qualität (1-5)",
        journal_density_rating: "Dichte (1-5)",
        journal_tags_label: "Tags (kommagetrennt)",
        journal_tags_placeholder: "z.B. LST, Entlaubung, Topping",
        journal_adjustments_edit_title: "Anpassungen bearbeiten",
        journal_remove_ai_analysis: "KI-Analyse entfernen",
        // New Journal Metrics
        journal_metrics_title: "Messwerte",
        journal_plant_height: "Pflanzenhöhe (cm)",
        journal_temp: "Temperatur (°C)",
        journal_humidity: "Luftfeuchtigkeit (%)",
        journal_ec: "EC",
        journal_ph: "pH",
        journal_leaf_temp: "Blatttemperatur (°C)",
        journal_vpd: "VPD (kPa)",
        journal_vwc: "VWC (%)",
        journal_soil_ec: "Boden EC",
        journal_plant_height_short: "Höhe",
        journal_temp_short: "Temp",
        journal_humidity_short: "LF",
        journal_leaf_temp_short: "Blatt",
        journal_vpd_short: "VPD",
        journal_vwc_short: "VWC",
        journal_soil_ec_short: "BodenEC",
        journal_chart_title: "Trendübersicht",
        journal_chart_no_data: "Noch keine Messwerte im Tagebuch vorhanden.",
        journal_chart_toggle_label: "Messreihen ein- oder ausblenden.",
        journal_chart_axis_date: "Datum",
        journal_chart_axis_value: "Messwert",
        journal_chart_tooltip_date: "Datum",
        journal_chart_tooltip_value: "Wert",
        journal_chart_metric_height: "Höhe (cm)",
        journal_chart_metric_temp: "Temperatur (°C)",
        journal_chart_metric_humidity: "Luftfeuchte (%)",
        journal_chart_metric_ec: "Trend (EC)",
        journal_chart_metric_ph: "pH-Verlauf",
        journal_chart_metric_leaf_temp: "Blatttemperatur (°C)",
        journal_chart_metric_vpd: "VPD (kPa)",
        journal_chart_metric_vwc: "VWC (%)",
        journal_chart_metric_soil_ec: "Boden EC",
        // Weigh Table Notes
        no_A_ripen: "Nicht in der Reifephase",
        not_in_veg: "nicht in Veg/Ripen",
        helix_pulse_note: "Helix zusätzlich 1×/Woche 0,3 ml/L für 24 h",
        ripen_only_note: "Nur in der Reifephase",
        // Plan Manager
        plan_manager_title: "Plan-Manager",
        plan_select_label: "Ausgewählter Plan",
        plan_name_label: "Planname",
        plan_name_placeholder: "z.B. Mein aggressiver Veg-Plan",
        plan_description_label: "Beschreibung",
        plan_description_placeholder: "z.B. Angepasst für hohes Licht...",
        plan_no_description: "Keine Beschreibung vorhanden.",
        plan_default: "Standardplan",
        plan_active_badge: "Aktiv",
        plan_save_as_button: "Speichern als...",
        plan_delete_button: "Löschen",
        plan_confirm_delete: "Möchten Sie diesen Plan wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
        plan_set_active_button: "Als Aktiv festlegen",
        plan_import_success: "Plan erfolgreich als '{0}' importiert.",
        plan_import_fail: "Import fehlgeschlagen: Ungültige Plandatei.",
        plan_default_is_readonly: "Der Standardplan ist schreibgeschützt. Um Änderungen vorzunehmen, verwenden Sie \"Speichern als...\", um eine benutzerdefinierte Kopie zu erstellen.",
        plan_create_new_title: "Neuen Plan erstellen",
        plan_save_new_button: "Neuen Plan speichern",
        plan_create_target_hint: "Wähle die Kombination aus Sorte und Substrat, für die der Plan gespeichert werden soll.",
        plan_create_cultivar_label: "Sorte",
        plan_create_substrate_label: "Substrat",
        plan_create_missing_name: "Bitte geben Sie einen Namen für den neuen Plan an.",
        plan_week_count_label: "Blütewochen",
        plan_week_count_hint: "Anzahl der Wochen (W1, W2, ...) im Plan.",
        plan_week_add: "Woche hinzufügen",
        plan_week_remove: "Letzte Woche entfernen",
        plan_week_duration: "Dauer (Tage)",
        water_profile_title: "Wasserprofil",
        water_profile_description: "Leitungswasserwerte in mg/L, die zu den berechneten PPM addiert werden.",
        water_osmosis_label: "Anteil Osmosewasser (%)",
        water_osmosis_hint: "Dieser Anteil reduziert die eingetragenen Wasserwerte proportional.",
        water_labels: {
            N: "Stickstoff (N)",
            Ca: "Calcium (Ca)",
            Mg: "Magnesium (Mg)",
            K: "Kalium (K)",
            Na: "Natrium (Na)",
            S: "Schwefel (S)",
            Cl: "Chlorid (Cl)",
            Fe: "Eisen (Fe)",
            Mn: "Mangan (Mn)",
        },
        nutrient_labels: {
            N: "Stickstoff (N)",
            P: "Phosphor (P)",
            K: "Kalium (K)",
            Ca: "Calcium (Ca)",
            Mg: "Magnesium (Mg)",
            S: "Schwefel (S)",
            Na: "Natrium (Na)",
            Fe: "Eisen (Fe)",
            B: "Bor (B)",
            Mo: "Molybdän (Mo)",
            Mn: "Mangan (Mn)",
            Zn: "Zink (Zn)",
            Cu: "Kupfer (Cu)",
            Cl: "Chlorid (Cl)",
        },
        optimizer_button: "KI-Plan Optimierung",
        optimizer_button_desc: "Erstellt einen Düngeplan aus Ziel-PPM-Vorgaben.",
        tooltip_optimizer: "Lass die KI einen neuen Düngeplan anhand deiner Zielwerte erstellen.",
        optimizer_default_plan_name: "KI-optimierter Plan",
        optimizer_modal_title: "KI-Plan Optimierung",
        optimizer_intro: "Definiere die Wochen, das Wachstumsstadium sowie die gewünschten ppm-Zielwerte. Die KI schlägt daraufhin passende Gramm-pro-Liter-Werte für A, B/C und BURST vor, die das Wasserprofil berücksichtigen.",
        optimizer_nutrient_select_label: "Ziel-Nährstoffe",
        optimizer_nutrient_select_hint: "Diese Nährstoffe werden der KI als Ziel-ppm vorgegeben.",
        optimizer_phase_header: "Phase",
        optimizer_stage_header: "Stadium",
        optimizer_target_unit: "ppm",
        optimizer_targets_hint: "ppm nach Mischung inkl. Wasserprofil.",
        optimizer_add_week: "Woche hinzufügen",
        optimizer_remove_week: "Woche entfernen",
        optimizer_water_section_title: "Wasser & Basiswerte",
        optimizer_water_section_hint: "Gib die ppm deines Ausgangswassers an. Der Osmose-Anteil reduziert diese Werte.",
        optimizer_osmosis_label: "Osmoseanteil (%)",
        optimizer_osmosis_hint: "0 % = nur Leitungswasser, 100 % = nur Osmosewasser.",
        optimizer_cancel_button: "Abbrechen",
        optimizer_run_button: "Plan optimieren",
        optimizer_result_summary_title: "Optimierungsergebnis",
        optimizer_result_no_summary: "Keine Zusammenfassung verfügbar.",
        optimizer_a_header: "A g/L",
        optimizer_x_header: "B/C g/L",
        optimizer_bz_header: "BURST g/L",
        optimizer_ph_header: "pH",
        optimizer_ec_header: "EC",
        optimizer_alignment_header: "Ziel-Abweichung",
        optimizer_notes_header: "Hinweise",
        optimizer_stage_label_short: "Stadium:",
        optimizer_alignment_missing: "Keine Zielwerte vorhanden.",
        optimizer_target_short: "Ziel",
        optimizer_actual_short: "Erreicht",
        optimizer_diff_short: "Δ",
        optimizer_plan_name_label: "Planname",
        optimizer_plan_name_placeholder: "z.B. KI-Blüteplan",
        optimizer_plan_description_label: "Beschreibung",
        optimizer_plan_description_placeholder: "Kurze Notizen zur Optimierung",
        optimizer_save_plan_button: "Plan speichern",
        optimizer_error_no_weeks: "Bitte füge mindestens eine Woche hinzu.",
        optimizer_error_no_nutrients: "Bitte wähle mindestens einen Nährstoff aus.",
        optimizer_error_missing_phase: "Bitte gib für jede Woche einen Namen an.",
        optimizer_error_targets_missing: "Für {0} wurden keine Zielwerte eingetragen.",
        optimizer_error_no_result: "Es liegt noch kein Optimierungsergebnis vor.",
        optimizer_error_name_required: "Bitte gib einen Namen für den neuen Plan an.",
        optimizer_stage_veg: "Vegetativ",
        optimizer_stage_flower: "Blüte",
        optimizer_stage_ripen: "Reife",
        grow_manager_title: "Anbau-Manager",
        new_grow: "Neuer Anbau",
        add_new_grow: "Neuen Anbau hinzufügen",
        grow_name: "Name des Anbaus",
        start_grow: "Anbau starten",
        no_grows_found: "Noch keine Anbauzyklen gestartet. Klicken Sie auf 'Neuer Anbau', um zu beginnen.",
        grow_delete_confirm: "Möchten Sie diesen Anbau wirklich löschen? Alle zugehörigen Tagebucheinträge bleiben erhalten, werden aber nicht mehr angezeigt.",
        back_to_grows: "Zurück zur Übersicht",
        compare_grows: "Vergleichen",
        grow_comparison_title: "Anbau-Vergleich",
        comparing_grows_desc: "Vergleich der Messwerte normiert auf den Anbautag",
        toggle_compare: "Zum Vergleich hinzufügen",
        day: "Tag",
        grow_settings: "Anbau-Einstellungen",
        ha_integration_title: "Home Assistant Integration",
        ha_integration_desc: "Verknüpfen Sie Messwerte mit Home Assistant Entitäten, um aktuelle Werte automatisch abzurufen.",
        loading_entities: "Lade Entitäten...",
        manual_input: "Manuelle Eingabe",
        save_settings: "Einstellungen speichern",
        fetch_ha_values: "Werte von HA abrufen",
        retry: "Erneut versuchen",
    },
    en: {
        lang: "Language",
        title: "PhotonFlux Nutrients Calculator",
        cultivar: "Cultivar",
        cultivar_names: {
            wedding_cake: "Wedding Cake",
            blue_dream: "Blue Dream",
            amnesia_haze: "Amnesia Haze",
        },
        substrate_names: {
            coco: "Coco",
            soil: "Soil",
            rockwool: "Rockwool",
        },
        phases: {
            "Early Veg": "Early Veg", "Mid Veg": "Mid Veg", "Late Veg": "Late Veg",
            "W1": "W1", "W2": "W2", "W3": "W3", "W4": "W4", "W5": "W5", "W6": "W6", "W7": "W7", "W8": "W8", "W9": "W9", "W10": "W10"
        },
        tags: {
            "Early Veg": "Seedling", "Mid Veg": "Growth", "Late Veg": "Growth",
            "W1": "Transformation", "W2": "Early Flower", "W3": "Early Flower", "W4": "Bulking", "W5": "Bulking", "W6": "Bulking", "W7": "Bulking", "W8": "Bulking", "W9": "Ripen", "W10": "Ripen"
        },
        days_of_week: {
            "0": "Sunday", "1": "Monday", "2": "Tuesday", "3": "Wednesday", "4": "Thursday", "5": "Friday", "6": "Saturday"
        },
        phase_week: "Phase/Week",
        settings: "Settings",
        reservoir: "Reservoir (L)",
        substrate: "Substrate",
        trend: "EC Trend",
        neutral: "Neutral",
        higher: "Higher",
        lower: "Lower",
        tipburn: "Tipburn",
        very_pale: "Very Pale",
        camg_need: "Ca/Mg Deficiency",
        claw: "The Claw",
        ph_drift: "pH Drift",
        normal: "Normal",
        too_high: "Too high",
        too_low: "Too low",
        start_date: "Start Date",
        auto_phase_switch: "Auto-Phase Switch",
        week_starts_on: "Week Starts On",
        calculate: "Calculate",
        calculating: "Calculating",
        reset: "Reset",
        export: "Export",
        import: "Import",
        config: "Plans",
        print: "Print",
        component: "Component",
        per_l: "per L",
        total: "Total",
        note: "Note",
        silicate_name: "Silicate / Hypo",
        per_plant_short: "plant",
        apply_per_plant: "Apply per plant",
        plan_print_title: "Printable Feeding Plan",
        plan_print_description: "Full schedule per liter with all components and notes.",
        plan_print_duration: "Duration (days)",
        plan_print_notes: "Notes",
        silicate_mid_veg_note: "Silicate topdress: distribute 4 g per plant around the plant.",
        target_ec: "Target EC:",
        npk_ratio_title: "NPK Ratio",
        edit_plan: "Edit Feed Plan",
        close: "Close",
        save: "Save",
        A_name: "A (Calcium Nitrate)", B_name: "B (N-P-K-Mg Salts)", C_name: "C (P-K-S-Mg Salts)", BURST_name: "BURST (PK Booster)",
        analyzer_button: "Plant Analyzer",
        analyzer_button_desc: "AI-powered issue detection",
        journal_button: "Grow Journal",
        journal_button_desc: "Track progress and notes",
        weekly_plan_title: "Weekly Plan",
        weekly_plan_prompt: "Set a start date to see the weekly plan.",
        current_week: "Current",
        tooltip_config: "Manage custom feed plans for the current cultivar and substrate.",
        tooltip_print: "Generate a printer-friendly version of the current results and weigh plan.",
        tooltip_trend: "How has the EC changed in the last 24h? Adjust feeding accordingly.",
        tooltip_phDrift: "How is the pH behaving in the nutrient solution? Drifting up or down can indicate issues.",
        tooltip_start_date: "The date the plant entered its first phase (seedling/clone). This enables the weekly schedule.",
        tooltip_auto_phase_switch: "When enabled, the app will automatically switch the phase based on the start date.",
        tooltip_week_starts_on: "Set the day of the week that each new grow week should begin for the auto-phase switch feature.",
        tooltip_tipburn: "Are leaf tips showing signs of burning? This often indicates a slight nutrient excess.",
        tooltip_claw: "Are leaves clawing downwards? A classic sign of Nitrogen excess.",
        tooltip_pale: "Are leaves, especially older ones, very pale or yellowish? This suggests a Nitrogen deficiency.",
        tooltip_caMgDeficiency: "Seeing rusty spots or light discoloration between leaf veins? This can indicate a Cal-Mag deficiency.",
        tooltip_calculate: "Calculates the final nutrient dosage based on all inputs and adjustments.",
        tooltip_reset: "Resets all inputs and plans to their default values.",
        tooltip_export: "Saves the selected feed plan as a JSON file.",
        tooltip_import: "Loads a feed plan from a JSON file as a new custom plan.",
        tooltip_A: "Core component: Primarily delivers Calcium and micronutrients.",
        tooltip_B: "Veg component: Delivers Nitrogen and Magnesium for the vegetative stage.",
        tooltip_C: "Bloom component: Delivers Sulfur and Magnesium for the flowering stage.",
        tooltip_burst: "Bloom booster: Provides Phosphorus and Potassium to enhance flower production.",
        tooltip_npk_ratio: "The ratio of Nitrogen (N), Phosphorus (P), and Potassium (K) in the final nutrient solution.",
        tooltip_analyzer: "Upload photos of your plant to get an AI-powered diagnosis of potential issues like deficiencies or pests.",
        tooltip_journal: "Keep a detailed log of every feeding, observation, and harvest to document your grow's progress.",
        // Mixing Instructions (Restored from doser.html)
        mixing_title: "Mixing Instructions",
        mixing_prep_title: "Preparation",
        mixing_prep_text1: "Fill tank 70–80% with water (18–22 °C), strong circulation on.",
        mixing_ph_title: "pH adjustment",
        mixing_ph_text1: "Never dump powders into the intake vortex. Make a slurry with 1–2 L tank water and add against the current.",
        mixing_veg_title: "Sequence – Veg (A + B)",
        mixing_veg_step1: "Add B (VECTOR) in 3 portions, stir, let clear 60–90 s.",
        mixing_veg_step2: "Add Helix, Ligand, Tide.",
        mixing_veg_step3: "Add A (CORE) last in 2 portions, slow. Mix 2 min, let clear.",
        mixing_veg_step4: "Top to final volume. Check EC & pH (Coco/RW: 5.8–6.0; Soil: 6.2–6.5).",
        mixing_bloom_title: "Sequence – Bloom (A + C + BURST)",
        mixing_bloom_step1: "Dissolve C (PULSE) in 3 portions.",
        mixing_bloom_step2: "Add BURST (PK) in 2 portions.",
        mixing_bloom_step3: "Add Helix, Ligand, Tide.",
        mixing_bloom_step4: "Add A (CORE) last in 2 portions.",
        mixing_bloom_step5: "Top to final volume. Check EC & pH.",
        mixing_checks_title: "Waiting times & checks",
        mixing_checks_step1: "Wait 60–120 s between components until clear.",
        mixing_checks_step2: "After A: run 2–3 min, then take stable EC.",
        analyzer_loading_step1: "Loading neural network...",
        analyzer_loading_step2: "Analyzing leaf morphology...",
        analyzer_loading_step3: "Checking for nutrient anomalies...",
        analyzer_loading_step4: "Compiling diagnosis...",
        analyzer_loading_wait: "Please wait, this may take a moment.",
        analyzer_fail_title: "Analysis Failed",
        analyzer_fail_try_again: "Try Again",
        analyzer_actions_title: "Recommended Actions",
        analyzer_another_photo: "Perform Another Analysis",
        analyzer_drop_zone: "Drop images here or",
        browse_files: "Browse files",
        analyzer_photos_added: "{0} / {1} photos added",
        analyzer_max_photos_remove: "Maximum reached. Remove one to add another.",
        analyzer_crop_photo: "Crop photo {0}",
        analyzer_remove_photo: "Remove photo {0}",
        analyzer_context_title: "Analysis Context",
        analyzer_phase: "Phase:",
        analyzer_substrate: "Substrate:",
        analyzer_notes_label: "Additional Notes",
        analyzer_notes_placeholder: "Describe the issue: where did it start? how has it progressed? E.g., 'Yellow spots on older leaves, spreading upwards'.",
        analyzer_button_cta: "Analyze Now",
        analyzer_disclaimer: "AI analysis is experimental and should be used as guidance, not a definitive diagnosis.",
        analyzer_title: "Plant Analyzer",
        ai_analysis_title: "AI Analysis",
        analyzer_invalid_file_alert: "Invalid file type for: {0}. Please upload images only.",
        analyzer_upload_limit_alert: "Upload limit of {0} photos reached. {1} file(s) were ignored.",
        analyzer_observed_symptoms_title: "Observed Symptoms",
        cropper_title: "Crop Image",
        cropper_cancel: "Cancel",
        cropper_save: "Save Crop",
        loading: "Loading...",
        cancel: "Cancel",
        date: "Date",
        phase: "Phase",
        ai_stage_analysis_title: "AI Stage Analysis",
        ai_stage_label: "Stage",
        ai_confidence_label: "Confidence",
        ai_reasoning_label: "Reasoning",
        ai_stage_loading: "Analyzing stage...",
        stage_vegetative: "Vegetative",
        stage_flowering: "Flowering",
        stage_ripening: "Ripening",
        confidence_High: "High",
        confidence_Medium: "Medium",
        confidence_Low: "Low",
        analyzer_summary_title: "Summary",
        analyzer_summary_finding: "Key Finding",
        analyzer_summary_action: "Top Recommendation",
        journal_title: "Grow Journal",
        journal_set_start_date_prompt: "Please set a start date in the main panel to create or view a grow journal.",
        journal_empty_state: "No entries yet. Add your first one!",
        journal_add_entry: "New Entry",
        journal_edit_entry: "Edit Entry",
        journal_entry_type: "Entry Type",
        journal_type_Observation: "Observation",
        journal_type_Feeding: "Feeding",
        journal_type_Pest: "Pest Control",
        journal_type_Training: "Training",
        journal_type_Harvest: "Harvest",
        journal_priority: "Priority",
        journal_priority_Critical: "Critical",
        journal_priority_High: "High",
        journal_priority_Medium: "Medium",
        journal_priority_Low: "Low",
        journal_notes_placeholder: "What happened today? Log your observations...",
        journal_add_photos: "Add Photos",
        journal_photos_added: "Photos Added",
        journal_save_entry: "Save Entry",
        journal_delete_entry: "Delete Entry",
        journal_confirm_delete: "Are you sure you want to delete this entry?",
        journal_feeding_details: "Feeding Details",
        journal_feeding_prefilled: "Values pre-filled based on the current plan.",
        journal_analyze_with_ai: "Analyze with AI",
        journal_ai_analysis_complete: "AI Analysis Complete",
        journal_ai_result: "AI Result",
        journal_filter_priority: "Filter by Priority",
        journal_all_priorities: "All",
        journal_week: "Week",
        journal_adjustments_title: "Adjustments",
        journal_save_analysis: "Save Analysis to Journal",
        journal_analysis_saved: "Analysis Saved",
        journal_export: "Export Journal",
        journal_ai_filter_label: "AI Analysis Only",
        journal_harvest_details: "Harvest Details",
        journal_wet_weight: "Wet Weight (g)",
        journal_dry_weight: "Dry Weight (g)",
        journal_trim_weight: "Trim Weight (g)",
        journal_quality_rating: "Quality (1-5)",
        journal_density_rating: "Density (1-5)",
        journal_tags_label: "Tags (comma-separated)",
        journal_tags_placeholder: "e.g. LST, Defoliation, Topped",
        journal_adjustments_edit_title: "Edit Adjustments",
        journal_remove_ai_analysis: "Remove AI Analysis",
        journal_metrics_title: "Metrics",
        journal_plant_height: "Plant Height (cm)",
        journal_temp: "Temperature (°C)",
        journal_humidity: "Humidity (%)",
        journal_ec: "EC",
        journal_ph: "pH",
        journal_leaf_temp: "Leaf Temperature (°C)",
        journal_vpd: "VPD (kPa)",
        journal_vwc: "VWC (%)",
        journal_soil_ec: "Soil EC",
        journal_plant_height_short: "Height",
        journal_temp_short: "Temp",
        journal_humidity_short: "RH",
        journal_leaf_temp_short: "Leaf",
        journal_vpd_short: "VPD",
        journal_vwc_short: "VWC",
        journal_soil_ec_short: "SoilEC",
        journal_chart_title: "Trend overview",
        journal_chart_no_data: "No journal metrics recorded yet.",
        journal_chart_toggle_label: "Toggle metric series.",
        journal_chart_axis_date: "Date",
        journal_chart_axis_value: "Value",
        journal_chart_tooltip_date: "Date",
        journal_chart_tooltip_value: "Value",
        journal_chart_metric_height: "Height (cm)",
        journal_chart_metric_temp: "Temperature (°C)",
        journal_chart_metric_humidity: "Humidity (%)",
        journal_chart_metric_ec: "Trend (EC)",
        journal_chart_metric_ph: "pH Trend",
        journal_chart_metric_leaf_temp: "Leaf Temp (°C)",
        journal_chart_metric_vpd: "VPD (kPa)",
        journal_chart_metric_vwc: "VWC (%)",
        journal_chart_metric_soil_ec: "Soil EC",
        no_A_ripen: "Not in ripen",
        not_in_veg: "not in veg/ripen",
        helix_pulse_note: "Helix additionally 1× weekly 0.3 ml/L for 24 h",
        ripen_only_note: "Ripen only",
        // Plan Manager
        plan_manager_title: "Plan Manager",
        plan_select_label: "Selected Plan",
        plan_name_label: "Plan Name",
        plan_name_placeholder: "e.g. My Aggressive Veg Plan",
        plan_description_label: "Description",
        plan_description_placeholder: "e.g. Adjusted for high light...",
        plan_no_description: "No description provided.",
        plan_default: "Default Plan",
        plan_active_badge: "Active",
        plan_save_as_button: "Save As...",
        plan_delete_button: "Delete",
        plan_confirm_delete: "Are you sure you want to delete this plan? This action cannot be undone.",
        plan_set_active_button: "Set as Active",
        plan_import_success: "Plan successfully imported as '{0}'.",
        plan_import_fail: "Import failed: Invalid plan file.",
        plan_default_is_readonly: "The default plan is read-only. To make changes, use \"Save As...\" to create a custom copy.",
        plan_create_new_title: "Create New Plan",
        plan_save_new_button: "Save New Plan",
        plan_create_target_hint: "Choose the cultivar and substrate the plan should belong to.",
        plan_create_cultivar_label: "Cultivar",
        plan_create_substrate_label: "Substrate",
        plan_create_missing_name: "Please provide a name for the new plan.",
        plan_week_count_label: "Flowering Weeks",
        plan_week_count_hint: "Number of weeks (W1, W2, ...) included in the plan.",
        plan_week_add: "Add week",
        plan_week_remove: "Remove last week",
        plan_week_duration: "Duration (days)",
        water_profile_title: "Water Profile",
        water_profile_description: "Tap water values in mg/L that are added to the calculated PPM.",
        water_osmosis_label: "RO Water Share (%)",
        water_osmosis_hint: "This share reduces the listed water values proportionally.",
        water_labels: {
            N: "Nitrogen (N)",
            Ca: "Calcium (Ca)",
            Mg: "Magnesium (Mg)",
            K: "Potassium (K)",
            Na: "Sodium (Na)",
            S: "Sulfur (S)",
            Cl: "Chloride (Cl)",
            Fe: "Iron (Fe)",
            Mn: "Manganese (Mn)",
        },
        nutrient_labels: {
            N: "Nitrogen (N)",
            P: "Phosphorus (P)",
            K: "Potassium (K)",
            Ca: "Calcium (Ca)",
            Mg: "Magnesium (Mg)",
            S: "Sulfur (S)",
            Na: "Sodium (Na)",
            Fe: "Iron (Fe)",
            B: "Boron (B)",
            Mo: "Molybdenum (Mo)",
            Mn: "Manganese (Mn)",
            Zn: "Zinc (Zn)",
            Cu: "Copper (Cu)",
            Cl: "Chloride (Cl)",
        },
        optimizer_button: "AI Plan Optimizer",
        optimizer_button_desc: "Generate a plan from target ppm goals.",
        tooltip_optimizer: "Let the AI draft a new feeding plan from your weekly targets.",
        optimizer_default_plan_name: "AI Optimized Plan",
        optimizer_modal_title: "AI Plan Optimization",
        optimizer_intro: "Define the weeks, growth stage and desired ppm values. The AI proposes gram-per-liter values for A, B/C and BURST while accounting for your water profile.",
        optimizer_nutrient_select_label: "Target nutrients",
        optimizer_nutrient_select_hint: "These nutrients will be treated as ppm targets for each week.",
        optimizer_phase_header: "Phase",
        optimizer_stage_header: "Stage",
        optimizer_target_unit: "ppm",
        optimizer_targets_hint: "ppm after mixing including water contribution.",
        optimizer_add_week: "Add week",
        optimizer_remove_week: "Remove week",
        optimizer_water_section_title: "Water & base values",
        optimizer_water_section_hint: "Enter the ppm of your source water. The RO share reduces these values.",
        optimizer_osmosis_label: "RO share (%)",
        optimizer_osmosis_hint: "0% = tap water only, 100% = reverse osmosis only.",
        optimizer_cancel_button: "Cancel",
        optimizer_run_button: "Optimize plan",
        optimizer_result_summary_title: "Optimization summary",
        optimizer_result_no_summary: "No summary available.",
        optimizer_a_header: "A g/L",
        optimizer_x_header: "B/C g/L",
        optimizer_bz_header: "BURST g/L",
        optimizer_ph_header: "pH",
        optimizer_ec_header: "EC",
        optimizer_alignment_header: "Target alignment",
        optimizer_notes_header: "Notes",
        optimizer_stage_label_short: "Stage:",
        optimizer_alignment_missing: "No target data.",
        optimizer_target_short: "Target",
        optimizer_actual_short: "Actual",
        optimizer_diff_short: "Δ",
        optimizer_plan_name_label: "Plan name",
        optimizer_plan_name_placeholder: "e.g. AI Bloom Plan",
        optimizer_plan_description_label: "Description",
        optimizer_plan_description_placeholder: "Optional notes about this optimization",
        optimizer_save_plan_button: "Save plan",
        optimizer_error_no_weeks: "Please add at least one week.",
        optimizer_error_no_nutrients: "Select at least one nutrient.",
        optimizer_error_missing_phase: "Please provide a name for each week.",
        optimizer_error_targets_missing: "No targets were provided for {0}.",
        optimizer_error_no_result: "No optimization result yet.",
        optimizer_error_name_required: "Please provide a name for the new plan.",
        optimizer_stage_veg: "Vegetative",
        optimizer_stage_flower: "Flower",
        optimizer_stage_ripen: "Ripen",
        grow_manager_title: "Grow Manager",
        new_grow: "New Grow",
        add_new_grow: "Add New Grow",
        grow_name: "Grow Name",
        start_grow: "Start Grow",
        no_grows_found: "No grows started yet. Click 'New Grow' to begin.",
        grow_delete_confirm: "Are you sure you want to delete this grow? Journal entries will be preserved but no longer visible here.",
        back_to_grows: "Back to List",
        compare_grows: "Compare",
        grow_comparison_title: "Grow Comparison",
        comparing_grows_desc: "Comparing metrics normalized by grow day",
        toggle_compare: "Toggle Compare",
        day: "Day",
        grow_settings: "Grow Settings",
        ha_integration_title: "Home Assistant Integration",
        ha_integration_desc: "Map metrics to Home Assistant entities to automatically fetch current values.",
        loading_entities: "Loading entities...",
        manual_input: "Manual Input",
        save_settings: "Save Settings",
        fetch_ha_values: "Fetch from HA",
        retry: "Retry",
    }
};

const BASE_PLAN_TEMPLATES: Record<Substrate, ManagedPlan> = {
  coco: {
    id: 'default',
    name: 'Default Plan',
    description: 'PhotonFlux baseline schedule for coco.',
    plan: [
      {phase:"Early Veg",A:0.8,X:0.8,BZ:0.00,pH:"5.7–5.9",EC:"1.7",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:4},
      {phase:"Mid Veg",A:1.0,X:1.0,BZ:0.00,pH:"5.7–5.9",EC:"1.9",Tide:0.30,Helix:0.02,Ligand:0.02,Silicate:4,SilicateUnit:'per_plant',notes:['silicate_mid_veg_note'],durationDays:5},
      {phase:"Late Veg",A:1.2,X:1.2,BZ:0.00,pH:"5.7–5.9",EC:"2.2",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:6},
      {phase:"W1",A:1.4,X:1.0,BZ:0.00,pH:"5.7–5.9",EC:"2.4",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:9},
      {phase:"W2",A:1.4,X:1.1,BZ:0.00,pH:"5.7–5.9",EC:"2.6",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:9},
      {phase:"W3",A:1.3,X:1.3,BZ:0.00,pH:"5.7–5.9",EC:"2.8",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:9},
      {phase:"W4",A:1.2,X:1.5,BZ:0.00,pH:"5.7–5.9",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:5},
      {phase:"W5",A:1.2,X:1.6,BZ:0.1,pH:"5.7–5.9",EC:"3.1",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:5},
      {phase:"W6",A:1.1,X:1.5,BZ:0.3,pH:"5.7–5.9",EC:"3.1",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:5},
      {phase:"W7",A:0.9,X:1.3,BZ:0.5,pH:"5.7–5.9",EC:"2.9",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W8",A:0.7,X:1.1,BZ:0.8,pH:"5.7–5.9",EC:"2.7",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W9",A:0.5,X:0.8,BZ:1.00,pH:"5.7–5.9",EC:"2.5",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:10},
      {phase:"W10",A:0.00,X:0.5,BZ:1.30,pH:"5.7–5.9",EC:"2.2",Tide:0.00,Helix:0.00,Ligand:0.00,durationDays:10}
    ],
    waterProfile: { ...DEFAULT_WATER_PROFILE },
    osmosisShare: DEFAULT_OSMOSIS_SHARES.coco,
    isDefault: true,
  },
  soil: {
    id: 'default',
    name: 'Default Plan',
    description: 'PhotonFlux baseline schedule for soil.',
    plan: [
      {phase:"Early Veg",A:0.7,X:0.25,BZ:0.00,pH:"5.8–6.2",EC:"1.7",Tide:0.20,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"Mid Veg",A:0.9,X:0.28,BZ:0.00,pH:"5.8–6.2",EC:"1.9",Tide:0.20,Helix:0.02,Ligand:0.02,Silicate:4,SilicateUnit:'per_plant',notes:['silicate_mid_veg_note'],durationDays:7},
      {phase:"Late Veg",A:1.1,X:0.31,BZ:0.00,pH:"5.8–6.2",EC:"2.2",Tide:0.20,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W1",A:1.23,X:0.35,BZ:0.10,pH:"5.8–6.2",EC:"2.4",Tide:0.20,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W2",A:1.32,X:0.35,BZ:0.17,pH:"5.8–6.2",EC:"2.6",Tide:0.20,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W3",A:1.32,X:0.35,BZ:0.23,pH:"5.8–6.2",EC:"2.8",Tide:0.20,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W4",A:1.32,X:0.46,BZ:0.21,pH:"5.8–6.2",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W5",A:1.19,X:0.46,BZ:0.21,pH:"5.8–6.2",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W6",A:1.19,X:0.46,BZ:0.21,pH:"5.8–6.2",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W7",A:1.02,X:0.58,BZ:0.09,pH:"5.8–6.2",EC:"2.8",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W8",A:0.80,X:0.52,BZ:0.09,pH:"5.8–6.2",EC:"2.6",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W9",A:0.58,X:0.45,BZ:0.06,pH:"5.8–6.2",EC:"1.6",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W10",A:0.00,X:0.36,BZ:0.00,pH:"5.8–6.2",EC:"1.0",Tide:0.00,Helix:0.00,Ligand:0.00,durationDays:7}
    ],
    waterProfile: { ...DEFAULT_WATER_PROFILE },
    osmosisShare: DEFAULT_OSMOSIS_SHARES.soil,
    isDefault: true,
  },
  rockwool: {
    id: 'default',
    name: 'Default Plan',
    description: 'PhotonFlux baseline schedule for rockwool.',
    plan: [
      {phase:"Early Veg",A:0.7,X:0.25,BZ:0.00,pH:"5.6–5.8",EC:"1.7",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"Mid Veg",A:0.9,X:0.28,BZ:0.00,pH:"5.6–5.8",EC:"1.9",Tide:0.30,Helix:0.02,Ligand:0.02,Silicate:4,SilicateUnit:'per_plant',notes:['silicate_mid_veg_note'],durationDays:7},
      {phase:"Late Veg",A:1.1,X:0.31,BZ:0.00,pH:"5.6–5.8",EC:"2.2",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W1",A:1.23,X:0.35,BZ:0.06,pH:"5.6–5.8",EC:"2.4",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W2",A:1.32,X:0.35,BZ:0.12,pH:"5.6–5.8",EC:"2.6",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W3",A:1.32,X:0.35,BZ:0.18,pH:"5.6–5.8",EC:"2.8",Tide:0.30,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W4",A:1.32,X:0.46,BZ:0.21,pH:"5.6–5.8",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W5",A:1.18,X:0.46,BZ:0.21,pH:"5.6–5.8",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W6",A:1.18,X:0.46,BZ:0.21,pH:"5.6–5.8",EC:"3.0",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W7",A:1.00,X:0.58,BZ:0.07,pH:"5.6–5.8",EC:"2.8",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W8",A:0.85,X:0.52,BZ:0.07,pH:"5.6–5.8",EC:"2.6",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W9",A:0.63,X:0.45,BZ:0.06,pH:"5.6–5.8",EC:"1.6",Tide:0.00,Helix:0.02,Ligand:0.02,durationDays:7},
      {phase:"W10",A:0.00,X:0.45,BZ:0.00,pH:"5.6–5.8",EC:"1.0",Tide:0.00,Helix:0.00,Ligand:0.00,durationDays:7}
    ],
    waterProfile: { ...DEFAULT_WATER_PROFILE },
    osmosisShare: DEFAULT_OSMOSIS_SHARES.rockwool,
    isDefault: true,
  },
};

const roundToTwoDecimals = (value: number): number => Math.round(value * 100) / 100;

const scalePlanEntries = (
  template: ManagedPlan,
  multipliers: { veg?: number; bloom?: number; ripen?: number },
): ManagedPlan['plan'] => {
  const { veg = 1, bloom = 1, ripen = 1 } = multipliers;
  return template.plan.map(entry => {
    const next = { ...entry };
    const weekMatch = /^W(\d+)$/.exec(entry.phase);
    const factor = weekMatch ? (Number(weekMatch[1]) >= 8 ? ripen : bloom) : veg;
    next.A = roundToTwoDecimals(next.A * factor);
    next.X = roundToTwoDecimals(next.X * factor);
    next.BZ = roundToTwoDecimals(next.BZ * factor);
    return next;
  });
};

const clonePlanTemplate = (plan: ManagedPlan, overrides: Partial<ManagedPlan> = {}): ManagedPlan => {
  const planEntries = overrides.plan ?? plan.plan;
  const waterProfile = overrides.waterProfile ?? plan.waterProfile;
  return {
    ...plan,
    ...overrides,
    plan: planEntries.map(entry => ({ ...entry })),
    waterProfile: { ...waterProfile },
    osmosisShare: overrides.osmosisShare ?? plan.osmosisShare,
    id: overrides.id ?? plan.id,
    isDefault: overrides.isDefault ?? plan.isDefault,
  };
};

const createCultivarPlan = (
  overrides: Partial<Record<Substrate, Partial<ManagedPlan>>> = {},
): Record<Substrate, ManagedPlan> => ({
  coco: clonePlanTemplate(BASE_PLAN_TEMPLATES.coco, overrides.coco),
  soil: clonePlanTemplate(BASE_PLAN_TEMPLATES.soil, overrides.soil),
  rockwool: clonePlanTemplate(BASE_PLAN_TEMPLATES.rockwool, overrides.rockwool),
});

export const DEFAULT_PLAN: Record<Cultivar, Record<Substrate, ManagedPlan>> = {
  wedding_cake: createCultivarPlan({
    coco: { description: 'PhotonFlux baseline schedule for Wedding Cake on coco.' },
    soil: { description: 'PhotonFlux baseline schedule for Wedding Cake on soil.' },
    rockwool: { description: 'PhotonFlux baseline schedule for Wedding Cake on rockwool.' },
  }),
  blue_dream: createCultivarPlan({
    coco: {
      description: 'Balanced feed plan tuned for Blue Dream in coco with a slight bloom emphasis.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.coco, { veg: 0.95, bloom: 1.05, ripen: 1 }),
    },
    soil: {
      description: 'Balanced feed plan tuned for Blue Dream in soil with a slight bloom emphasis.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.soil, { veg: 0.95, bloom: 1.05, ripen: 1 }),
    },
    rockwool: {
      description: 'Balanced feed plan tuned for Blue Dream in rockwool with a slight bloom emphasis.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.rockwool, { veg: 0.95, bloom: 1.05, ripen: 1 }),
    },
  }),
  amnesia_haze: createCultivarPlan({
    coco: {
      description: 'Gentle feed schedule crafted for Amnesia Haze in coco to support long flowering.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.coco, { veg: 0.9, bloom: 0.94, ripen: 0.85 }),
    },
    soil: {
      description: 'Gentle feed schedule crafted for Amnesia Haze in soil to support long flowering.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.soil, { veg: 0.9, bloom: 0.94, ripen: 0.85 }),
    },
    rockwool: {
      description: 'Gentle feed schedule crafted for Amnesia Haze in rockwool to support long flowering.',
      plan: scalePlanEntries(BASE_PLAN_TEMPLATES.rockwool, { veg: 0.9, bloom: 0.94, ripen: 0.85 }),
    },
  }),
};


// FIX: Added missing micronutrient properties to each stage to satisfy the TypeScript type.
export const NUTRIENT_TARGET_RANGES: Record<StageClass, Record<keyof NutrientProfile, { min: number; max: number }>> = {
  VEG: { 
    N: { min: 140, max: 180 }, P: { min: 40, max: 60 }, K: { min: 120, max: 160 }, Ca: { min: 100, max: 140 }, Mg: { min: 45, max: 65 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
  B1: { 
    N: { min: 160, max: 200 }, P: { min: 50, max: 70 }, K: { min: 150, max: 200 }, Ca: { min: 120, max: 160 }, Mg: { min: 50, max: 70 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
  P23: { 
    N: { min: 150, max: 190 }, P: { min: 60, max: 80 }, K: { min: 180, max: 240 }, Ca: { min: 120, max: 160 }, Mg: { min: 55, max: 75 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
  P47: { 
    N: { min: 140, max: 180 }, P: { min: 70, max: 90 }, K: { min: 200, max: 260 }, Ca: { min: 120, max: 160 }, Mg: { min: 60, max: 80 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
  W8: { 
    N: { min: 100, max: 140 }, P: { min: 60, max: 80 }, K: { min: 180, max: 240 }, Ca: { min: 100, max: 140 }, Mg: { min: 50, max: 70 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
  RIPEN: { 
    N: { min: 0, max: 50 }, P: { min: 40, max: 60 }, K: { min: 100, max: 150 }, Ca: { min: 80, max: 120 }, Mg: { min: 30, max: 50 }, S: { min: 0, max: 0 },
    Na: { min: 0, max: 0 }, Fe: { min: 0, max: 0 }, B: { min: 0, max: 0 }, Mo: { min: 0, max: 0 }, Mn: { min: 0, max: 0 }, Zn: { min: 0, max: 0 }, Cu: { min: 0, max: 0 }, Cl: { min: 0, max: 0 }
  },
};
